### ISSUE TITLE
HTTP-error: 500, POST route //egresos & //productos. Multiple notifications on error

### ISSUE THREAD

**Issue by gusram01** [renato-castillo/minicrud-ng#1]
# Error en lanzar petición POST

## Cuando intento guardar un nuevo egreso o producto recibo un error POST-500

- No se si tenga que ver con la autenticación o con algún error en el servicio.

## El evento de enviar formulario esta activo y se pueden realizar múltiples peticiones aún con error.

![error-500](https://firebasestorage.googleapis.com/v0/b/nglogingus.appspot.com/o/error500.png?alt=media&token=43eda031-65e7-46c0-9867-188f7b3d1b0e)

**Comment by renato-castillo** [comment]
![image](https://user-images.githubusercontent.com/65872627/107412270-7e0c8b00-6add-11eb-8435-8a3ca2a521cf.png)

Problema solucionado, un pequeño problema en el lado del back.
